#!/bin/sh
# Pick the lowest-load Proton NL P2P servers from the proton-gluetun-updater
# cache and export SERVER_NAMES via /shared/env. Runs at container startup
# before the main entrypoint sources /shared/env.
#
# Inputs (env):
#   PICKER_CACHE_DIR   directory containing the cache, default /gluetun/proton
#   PICKER_COUNTRY     ExitCountry to filter on, default NL
#   PICKER_TIER        Proton Tier to require (2=paid Plus), default 2
#   PICKER_TOP_N       how many lowest-load servers to keep, default 10
#   PICKER_P2P_ONLY    if "true" (default), require the P2P feature bit
#
# Output:
#   /shared/env gets a `SERVER_NAMES="NL#316,NL#412,..."` line appended.
#
# Safe to re-run: rewrites /shared/env from scratch.
#
# Cache-miss policy: log a warning and exit 0 without setting SERVER_NAMES.
# The Gluetun main entrypoint will then fall back to SERVER_COUNTRIES picking
# from the embedded list. The picker re-runs on every pod restart, so once
# proton-gluetun-updater has written a cache, the next pod cycle uses it.

set -eu

CACHE_DIR="${PICKER_CACHE_DIR:-/gluetun/proton}"
COUNTRY="${PICKER_COUNTRY:-NL}"
TIER="${PICKER_TIER:-2}"
TOP_N="${PICKER_TOP_N:-10}"
P2P_ONLY="${PICKER_P2P_ONLY:-true}"
SHARED_ENV="/shared/env"

mkdir -p "$(dirname "$SHARED_ENV")"

# Pick the newest serverlist.<epoch>.json — proton-gluetun-updater rotates 3
# files, so this is always the freshest snapshot it has.
cache_file=$(find "$CACHE_DIR" -maxdepth 1 -name 'serverlist.*.json' -type f 2>/dev/null | sort -r | head -n1)

if [ -z "$cache_file" ] || [ ! -s "$cache_file" ]; then
    echo "pick-servers: no cache file under $CACHE_DIR — falling back to SERVER_COUNTRIES (no SERVER_NAMES pin)"
    exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "pick-servers: jq not installed, cannot parse $cache_file — falling back to SERVER_COUNTRIES"
    exit 0
fi

# Bitmask reminder (from proton-gluetun-updater/internal/transform):
#   SECURE_CORE=1  TOR=2  P2P=4  STREAMING=8
# We require the P2P bit set (Features & 4 != 0) and exclude Secure Core
# (Features & 1 == 0) because secure-core servers route through a second hop
# and are slower.
if [ "$P2P_ONLY" = "true" ]; then
    feature_filter='(.Features // 0) as $f | ($f / 4 | floor % 2 == 1) and ($f % 2 == 0)'
else
    feature_filter='true'
fi

# Pull the .Name field of the TOP_N lowest-load matches, joined as CSV.
# Default Load to 100 if missing, matching the Python transform's fallback.
names=$(jq -r \
    --arg country "$COUNTRY" \
    --argjson tier "$TIER" \
    --argjson top "$TOP_N" \
    "[.LogicalServers[]
        | select(.ExitCountry == \$country)
        | select(.Tier == \$tier)
        | select($feature_filter)
        | {name: .Name, load: (.Load // 100)}
     ]
     | sort_by(.load)
     | .[0:\$top]
     | map(.name)
     | join(\",\")
    " "$cache_file" 2>/dev/null || echo "")

if [ -z "$names" ]; then
    echo "pick-servers: jq returned no matches in $cache_file (country=$COUNTRY tier=$TIER p2p=$P2P_ONLY) — falling back to SERVER_COUNTRIES"
    exit 0
fi

count=$(echo "$names" | tr ',' '\n' | wc -l | tr -d ' ')
cache_age_min=$(( ( $(date +%s) - $(basename "$cache_file" .json | sed 's/serverlist\.//') ) / 60 ))
echo "pick-servers: selected $count lowest-load $COUNTRY tier-$TIER servers (cache $cache_age_min min old)"
echo "pick-servers: SERVER_NAMES=$names"

# Write to /shared/env — the main entrypoint sources this before exec'ing
# /gluetun-entrypoint, so SERVER_NAMES enters Gluetun's env naturally.
{
    echo "# Generated by /pick-servers.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: $cache_file ($cache_age_min min old)"
    echo "export SERVER_NAMES='$names'"
} > "$SHARED_ENV"
