name: Build and Push Release Image
description: Builds and pushes the multi-arch image to a registry

inputs:
  app:
    required: true
    description: "App to build for"
  channel:
    required: true
    description: "Channel to build for"
  upstream_version:
    required: true
    description: "Upstream version to build"
  dockerfile:
    required: true
    description: "Dockerfile path"
  label_type:
    required: true
    description: "Label type to use"
  build_date:
    required: true
    description: "Build date"
  tag_rolling:
    required: true
    description: "Tag for rolling"
  tag_version:
    required: true
    description: "Tag version"
  platforms:
    required: true
    description: "Platforms to build for"
  push:
    required: false
    default: "true"
    description: "Push the image to the registry"
  token:
    required: true
    description: "GitHub token for authentication"
  public_token:
    required: true
    description: "GitHub token for authentication (public packages)"

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        secrets: |
          "PUBLIC_PACKAGES_TOKEN=${{ inputs.public_token }}"
        build-args: |
          VERSION=${{ inputs.upstream_version }}
          CHANNEL=${{ inputs.channel }}
        labels: |
          ${{ inputs.label_type }}.created=${{ inputs.build_date }}
          ${{ inputs.label_type }}.title=${{ inputs.app }} (${{ inputs.channel }})
          ${{ inputs.label_type }}.version=${{ inputs.upstream_version }}
          ${{ inputs.label_type }}.authors=iPromKnight <promknight@proton.me>
          ${{ inputs.label_type }}.url=https://github.com/ipromknight/containers/apps/${{ inputs.app }}
          ${{ inputs.label_type }}.build.url=https://github.com/ipromknight/containers/actions/runs/${{ github.run_id }}
          ${{ inputs.label_type }}.documentation=https://github.com/ipromknight/containers/apps/${{ inputs.app }}/README.md
          ${{ inputs.label_type }}.revision=${{ github.sha }}
        context: .
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/ipromknight/${{ inputs.tag_rolling }}
          ghcr.io/ipromknight/${{ inputs.tag_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max